# ansible/roles/pfc-nginx/tasks/main.yml
---

- name: Adding nginx-full ppa
  apt_repository: >
    repo="ppa:nginx/stable"
    update_cache=yes

- name: Installing nginx-full
  apt: >
    name=nginx-full
    state=latest

- name: Copy the nginx configuration file
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf