# ansible/roles/pfc-mysql/tasks/main.yml
---

- name: Installing mysql-server and dependencies
  apt: >
    name={{item}}
    state=latest
  with_items:
    - mysql-server
    - python-mysqldb

- name: Ensuring mysql is started at boot
  service: >
    name=mysql
    state=started
    enabled=yes

- name: Setting the mysql root password
  mysql_user:
    user: root
    host: "{{item}}"
    password: "{{mysql_root_password}}"
  with_items:
   - "{{ansible_hostname}}"
   - 127.0.0.1
   - ::1
   - localhost

- name: Setting mysql passwordless root access
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600