# ansible/roles/pfc-drupal-conf/tasks/main.yml
---

- name: Creating the MySQL db for drupal
  mysql_db: >
    db={{ drupal_db }}
    state=present

- name: Creating a MySQL user for drupal
  mysql_user: >
    name={{ drupal_db_user }}
    host={{ item }}
    priv={{ drupal_db }}.*:ALL
    password={{ drupal_db_pass }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Installing drush
  apt: >
     name=drush
     state=latest

- name: Configuring drupal settings.php with drush
  shell: >
    drush si standard -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_admin_name }}
    --account-pass={{ drupal_admin_pass }}
    --db-url=mysql://{{ drupal_db_user }}:{{ drupal_db_pass }}@localhost/{{ drupal_db }}
    chdir={{ drupal_path }}
    creates={{ drupal_path }}/sites/default/settings.php

- name: Adding nginx site conf file
  template: >
    src=nginx-vhost.conf.j2
    dest=/etc/nginx/sites-available/nginx-vhost.conf
    owner=root
    group=root
    mode=644
  notify: reload nginx

- name: Enabling nginx site and reload the webserver
  file: >
    src=/etc/nginx/sites-available/nginx-vhost.conf
    dest=/etc/nginx/sites-enabled/nginx-vhost.conf
    state=link
  notify: reload nginx

- name: Disabling nginx default site
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify: reload nginx