# ansible/roles/pfc-drupal-conf/tasks/main.yml
---

- name: Creating the MySQL db for drupal
  mysql_db: >
    db={{ drupal_db }}
    state=present

- name: Creating a MySQL user for drupal
  mysql_user: >
    name={{ drupal_db_user }}
    host={{ item }}
    priv={{ drupal_db }}.*:ALL
    password={{ drupal_db_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Installing drush
  apt: >
     name=drush
     state=latest

- name: Installing drupal with drush
  command: >
    drush si standard -y
    --db-url=mysql://{{ drupal_db_user }}:{{ drupal_db_password }}@localhost/{{ drupal_db }}
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_admin_name }}
    --account-pass={{ drupal_admin_pass }}
    chdir={{ drupal_path }}
    creates={{ drupal_path }}/sites/default/settings.php



